[package]
name = "vm_config"
version = "0.1.0"

[dependencies]
log = "0.4"
serde-json-core = "0.5.1"
serde = { version = "1.0", default-features = false, features = ["derive"] }
heapless = { version = "0.8.0", features = ["serde"] }
spin = "0.9"